# Generated by Django 5.2.17 on 2026-09-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('auto', 'Auto'), ('home', 'Home'), ('life', 'Life'), ('commercial', 'Commercial'), ('specialty', 'Specialty / HNW'), ('nonstandard_auto', 'Non-standard Auto'), ('collector', 'Collector'), ('travel', 'Travel'), ('disability', 'Disability'), ('residual', 'Residual Market')], max_length=32)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('name', 'group'), name='items_name_group_uniq'), models.CheckConstraint(condition=models.Q(('annual_price__isnull', True), ('annual_price__gte', 0), _connector='OR'), name='items_annual_price_nonneg'), models.CheckConstraint(condition=models.Q(('monthly_price__isnull', True), ('monthly_price__gte', 0), _connector='OR'), name='items_monthly_price_nonneg')],
            },
        ),
    ]
