# Generated by Django 5.2.17 on 2026-09-08 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('annual_price',), name='items_annual_price_uniq'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('monthly_price',), name='items_monthly_price_uniq'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('created_at',), name='items_created_at_uniq'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('updated_at',), name='items_updated_at_uniq'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('annual_price__isnull', True), ('monthly_price__isnull', True), models.Q(('annual_price', models.F('monthly_price')), _negated=True), _connector='OR'), name='items_annual_ne_monthly'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('created_at', models.F('updated_at')), _negated=True), name='items_created_ne_updated'),
        ),
    ]
